// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CorrR
arma::cube CorrR(arma::vec& y, arma::mat& x, arma::vec& beta, int n, arma::vec& k, char corre);
RcppExport SEXP _interep_CorrR(SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP nSEXP, SEXP kSEXP, SEXP correSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< char >::type corre(correSEXP);
    rcpp_result_gen = Rcpp::wrap(CorrR(y, x, beta, n, k, corre));
    return rcpp_result_gen;
END_RCPP
}
// ScoreU
Rcpp::List ScoreU(int n, arma::vec& k, arma::vec& y, arma::mat& x, int p, arma::vec& beta, arma::cube& Rhat);
RcppExport SEXP _interep_ScoreU(SEXP nSEXP, SEXP kSEXP, SEXP ySEXP, SEXP xSEXP, SEXP pSEXP, SEXP betaSEXP, SEXP RhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Rhat(RhatSEXP);
    rcpp_result_gen = Rcpp::wrap(ScoreU(n, k, y, x, p, beta, Rhat));
    return rcpp_result_gen;
END_RCPP
}
// dmcp
arma::vec dmcp(arma::vec& theta, double lambda, double gamma);
RcppExport SEXP _interep_dmcp(SEXP thetaSEXP, SEXP lambdaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(dmcp(theta, lambda, gamma));
    return rcpp_result_gen;
END_RCPP
}
// interep
arma::vec interep(arma::mat& e, arma::mat& z, arma::mat& y0, arma::vec& beta, double lam1, double lam2, char corre, int maxits);
RcppExport SEXP _interep_interep(SEXP eSEXP, SEXP zSEXP, SEXP y0SEXP, SEXP betaSEXP, SEXP lam1SEXP, SEXP lam2SEXP, SEXP correSEXP, SEXP maxitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type lam1(lam1SEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< char >::type corre(correSEXP);
    Rcpp::traits::input_parameter< int >::type maxits(maxitsSEXP);
    rcpp_result_gen = Rcpp::wrap(interep(e, z, y0, beta, lam1, lam2, corre, maxits));
    return rcpp_result_gen;
END_RCPP
}
// reformat
Rcpp::List reformat(arma::mat& y, arma::mat& x);
RcppExport SEXP _interep_reformat(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(reformat(y, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_interep_CorrR", (DL_FUNC) &_interep_CorrR, 6},
    {"_interep_ScoreU", (DL_FUNC) &_interep_ScoreU, 7},
    {"_interep_dmcp", (DL_FUNC) &_interep_dmcp, 3},
    {"_interep_interep", (DL_FUNC) &_interep_interep, 8},
    {"_interep_reformat", (DL_FUNC) &_interep_reformat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_interep(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
